@baseServer = https://localhost:7077/

### Health check
GET {{baseServer}}/api/healthz


### T1
POST {{baseServer}}
Content-Type: application/json
Accept: application/json, text/event-stream

{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "tools/list",
   "params": {}
}
